spring:
  profiles: ec2
---
spring:
  main:
    banner-mode: "off"
  devtools:
    add-properties: false
owm:
  appid: 659c58547457aff55894e298a3f85ac3
  url: http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={appid}